-- Adventure feedback schema for closed attempts.

CREATE TABLE IF NOT EXISTS public.adventure_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT NOT NULL UNIQUE REFERENCES public.adventure_attempts(id) ON DELETE CASCADE,
    adventure_id BIGINT NOT NULL REFERENCES public.adventures(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    difficulty_rating INT NOT NULL,
    overall_rating INT NOT NULL,
    custom_feedback TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT adventure_feedback_difficulty_rating_range CHECK (difficulty_rating BETWEEN 1 AND 5),
    CONSTRAINT adventure_feedback_overall_rating_range CHECK (overall_rating BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS adventure_feedback_adventure_id_idx
    ON public.adventure_feedback(adventure_id);

CREATE INDEX IF NOT EXISTS adventure_feedback_user_id_idx
    ON public.adventure_feedback(user_id);

ALTER TABLE public.adventure_feedback ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "adventure_feedback_own_only" ON public.adventure_feedback;
DROP POLICY IF EXISTS "adventure_feedback_accessible" ON public.adventure_feedback;
CREATE POLICY "adventure_feedback_accessible" ON public.adventure_feedback
    FOR ALL USING (true)
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.adventure_attempts
            WHERE public.adventure_attempts.id = adventure_feedback.attempt_id
              AND public.adventure_attempts.adventure_id = adventure_feedback.adventure_id
              AND public.adventure_attempts.user_id = adventure_feedback.user_id
              AND public.adventure_attempts.completed_at IS NOT NULL
        )
    );
