-- ============================================================================
-- PHASE 1: Quiz, Users, Points & Progress Schema for clue-venture
-- ============================================================================

-- ============================================================================
-- 1. USERS TABLE - User Authentication & Profiles
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    username TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT email_format CHECK (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')
);

CREATE INDEX IF NOT EXISTS users_email_idx ON public.users(email);

-- ============================================================================
-- 2. USER PROFILES - Points & Stats Tracking
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.user_profiles (
    user_id UUID PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
    total_points INT NOT NULL DEFAULT 0,
    adventures_completed INT NOT NULL DEFAULT 0,
    adventures_started INT NOT NULL DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT total_points_non_negative CHECK (total_points >= 0)
);

-- ============================================================================
-- 3. QUIZ QUESTIONS - Quiz Content per Adventure
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adventure_id BIGINT NOT NULL REFERENCES public.adventures(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    order_index INT NOT NULL,
    question_type TEXT NOT NULL DEFAULT 'multiple_choice',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT quiz_questions_order_index_non_negative CHECK (order_index >= 0),
    CONSTRAINT quiz_questions_order_unique UNIQUE(adventure_id, order_index)
);

CREATE INDEX IF NOT EXISTS quiz_questions_adventure_id_idx ON public.quiz_questions(adventure_id);

-- ============================================================================
-- 4. QUIZ ANSWERS - ABCD Answers for Quiz Questions
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.quiz_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES public.quiz_questions(id) ON DELETE CASCADE,
    answer_text TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    answer_order INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT quiz_answers_order_non_negative CHECK (answer_order >= 0),
    CONSTRAINT quiz_answers_order_unique UNIQUE(question_id, answer_order)
);

CREATE INDEX IF NOT EXISTS quiz_answers_question_id_idx ON public.quiz_answers(question_id);

-- ============================================================================
-- 5. ADVENTURE ATTEMPTS - User Adventure Tracking (Multiple Attempts Allowed)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.adventure_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adventure_id BIGINT NOT NULL REFERENCES public.adventures(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    completed_at TIMESTAMP WITH TIME ZONE,
    started_checkpoint_index INT NOT NULL DEFAULT 0,
    current_checkpoint_index INT NOT NULL DEFAULT 0,
    points_earned INT DEFAULT 0,
    time_spent_seconds INT,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT points_earned_non_negative CHECK (points_earned >= 0),
    CONSTRAINT checkpoint_index_non_negative CHECK (current_checkpoint_index >= 0 AND started_checkpoint_index >= 0)
);

CREATE INDEX IF NOT EXISTS adventure_attempts_adventure_id_idx ON public.adventure_attempts(adventure_id);
CREATE INDEX IF NOT EXISTS adventure_attempts_user_id_idx ON public.adventure_attempts(user_id);
CREATE INDEX IF NOT EXISTS adventure_attempts_created_idx ON public.adventure_attempts(started_at DESC);

-- ============================================================================
-- 6. USER ANSWERS - Quiz Response Tracking per Attempt
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.user_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT NOT NULL REFERENCES public.adventure_attempts(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES public.quiz_questions(id) ON DELETE CASCADE,
    answer_id BIGINT NOT NULL REFERENCES public.quiz_answers(id) ON DELETE CASCADE,
    is_correct BOOLEAN NOT NULL,
    answered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT user_answers_attempt_question_unique UNIQUE(attempt_id, question_id)
);

CREATE INDEX IF NOT EXISTS user_answers_attempt_id_idx ON public.user_answers(attempt_id);
CREATE INDEX IF NOT EXISTS user_answers_question_id_idx ON public.user_answers(question_id);

-- ============================================================================
-- 7. USER PROGRESS - Real-time Progress during Adventure (Transient Data)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.user_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT NOT NULL UNIQUE REFERENCES public.adventure_attempts(id) ON DELETE CASCADE,
    current_checkpoint_index INT NOT NULL DEFAULT 0,
    last_location_latitude DOUBLE PRECISION,
    last_location_longitude DOUBLE PRECISION,
    last_location_update TIMESTAMP WITH TIME ZONE,
    reached_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT checkpoint_index_non_negative CHECK (current_checkpoint_index >= 0),
    CONSTRAINT valid_coordinates CHECK (
        (last_location_latitude IS NULL AND last_location_longitude IS NULL) OR
        (last_location_latitude >= -90 AND last_location_latitude <= 90 AND
         last_location_longitude >= -180 AND last_location_longitude <= 180)
    )
);

CREATE INDEX IF NOT EXISTS user_progress_attempt_id_idx ON public.user_progress(attempt_id);

-- ============================================================================
-- POLICIES: Enable RLS for Data Protection
-- ============================================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.adventure_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_answers ENABLE ROW LEVEL SECURITY;

-- Policy: The current app manages its own user records client-side
DROP POLICY IF EXISTS "users_readable" ON public.users;
CREATE POLICY "users_readable" ON public.users
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "users_insertable" ON public.users;
CREATE POLICY "users_insertable" ON public.users
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "users_updatable" ON public.users;
CREATE POLICY "users_updatable" ON public.users
    FOR UPDATE USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "user_profiles_readable" ON public.user_profiles;
CREATE POLICY "user_profiles_readable" ON public.user_profiles
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "user_profiles_insertable" ON public.user_profiles;
CREATE POLICY "user_profiles_insertable" ON public.user_profiles
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "user_profiles_updatable" ON public.user_profiles;
CREATE POLICY "user_profiles_updatable" ON public.user_profiles
    FOR UPDATE USING (true) WITH CHECK (true);

-- Policy: Users can read and write quiz data
-- The app uses custom auth (not Supabase Auth), so access is governed by app logic.
DROP POLICY IF EXISTS "quiz_questions_readable" ON public.quiz_questions;
CREATE POLICY "quiz_questions_readable" ON public.quiz_questions
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "quiz_questions_writable" ON public.quiz_questions;
CREATE POLICY "quiz_questions_writable" ON public.quiz_questions
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "quiz_answers_readable" ON public.quiz_answers;
CREATE POLICY "quiz_answers_readable" ON public.quiz_answers
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "quiz_answers_writable" ON public.quiz_answers;
CREATE POLICY "quiz_answers_writable" ON public.quiz_answers
    FOR ALL USING (true) WITH CHECK (true);

-- Policy: The current app manages custom users client-side instead of Supabase Auth.
-- These tables must be accessible to the anon client; ownership is enforced by app logic.
DROP POLICY IF EXISTS "attempts_own_only" ON public.adventure_attempts;
DROP POLICY IF EXISTS "adventure_attempts_accessible" ON public.adventure_attempts;
CREATE POLICY "adventure_attempts_accessible" ON public.adventure_attempts
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "user_answers_own_only" ON public.user_answers;
DROP POLICY IF EXISTS "user_answers_accessible" ON public.user_answers;
CREATE POLICY "user_answers_accessible" ON public.user_answers
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "progress_own_only" ON public.user_progress;
DROP POLICY IF EXISTS "user_progress_accessible" ON public.user_progress;
CREATE POLICY "user_progress_accessible" ON public.user_progress
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "profiles_own_only" ON public.user_profiles;
DROP POLICY IF EXISTS "user_profiles_accessible" ON public.user_profiles;
CREATE POLICY "user_profiles_accessible" ON public.user_profiles
    FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- ADDITIONAL: CASCADE delete for data consistency
-- ============================================================================

ALTER TABLE public.quiz_questions
    DROP CONSTRAINT IF EXISTS quiz_questions_adventure_id_fkey,
    ADD CONSTRAINT quiz_questions_adventure_id_fkey
        FOREIGN KEY (adventure_id) REFERENCES public.adventures(id) ON DELETE CASCADE;

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Atomic point increment with upsert — creates the row if it doesn't exist yet.
CREATE OR REPLACE FUNCTION public.increment_user_points(p_user_id UUID, p_delta INT)
RETURNS VOID
LANGUAGE SQL
AS $$
    INSERT INTO public.user_profiles (user_id, total_points)
    VALUES (p_user_id, p_delta)
    ON CONFLICT (user_id)
    DO UPDATE SET
        total_points  = user_profiles.total_points + EXCLUDED.total_points,
        last_updated  = now();
$$;

GRANT EXECUTE ON FUNCTION public.increment_user_points(UUID, INT) TO anon;
GRANT EXECUTE ON FUNCTION public.increment_user_points(UUID, INT) TO authenticated;

-- ============================================================================
-- DONE
-- ============================================================================
