-- Adventure schema update for create flow with multiple locations.

ALTER TABLE public.adventures
    ADD COLUMN IF NOT EXISTS difficulty text,
    ADD COLUMN IF NOT EXISTS estimated_duration_minutes integer;

CREATE TABLE IF NOT EXISTS public.adventure_locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adventure_id bigint NOT NULL REFERENCES public.adventures(id) ON DELETE CASCADE,
    name text NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    order_index integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT adventure_locations_order_index_non_negative CHECK (order_index >= 0),
    CONSTRAINT adventure_locations_latitude_range CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT adventure_locations_longitude_range CHECK (longitude >= -180 AND longitude <= 180)
);

CREATE INDEX IF NOT EXISTS adventure_locations_adventure_id_idx
    ON public.adventure_locations(adventure_id);

CREATE UNIQUE INDEX IF NOT EXISTS adventure_locations_adventure_order_idx
    ON public.adventure_locations(adventure_id, order_index);
